server:
  port: 8006
spring:

  application:
    name: cloud-provide-paymentconsul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

