server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com
  client:
    #表示自己不用想自己注册
    register-with-eureka: false
    #自己就是注册中心，我的职责就是维护实例，并不用去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka servier交互的地址和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
  server:
    #关闭7003的自我保护机制
    enable-self-preservation: false
    #修改多少毫秒没有接受到心跳就删除服务
    eviction-interval-timer-in-ms: 2000