server:
  port: 84
spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719



management:
  endpoints:
    web:
      exposure:
        include: "*"

service-url:
  nacos-user-servic: http://nacos-payment-provider
feign:
  sentinel:
    enabled: true