server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: cloud_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seata_order
    type: com.alibaba.druid.pool.DruidDataSource
feign:
  hystrix:
    enabled: true
logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
